---
- name: Run Setup
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: DEPENDENCIES
      include_tasks: dependencies.yml

    - name: HOMEBREW (Install Packages + Update Homebrew)
      include_tasks: homebrew.yml

    - name: MAC APP STORE (Install Apps + Upgrade All)
      include_tasks: mas.yml

    - name: FOLDERS
      include_tasks: setup_dev_folder.yml
      
    - name: DOCK
      include_tasks: dock.yml
